import { Navbar } from '@/components/Navbar';
import { RwaDashboard } from '@/components/features/Dashboard';
import { SwapInterface } from '@/components/features/Swap';
import { StakingInterface } from '@/components/features/Staking';

export default function Home() {
  return (
    <main className="min-h-screen pt-24 pb-12 px-6 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-slate-950 to-black">
      <Navbar />

      <div className="container mx-auto max-w-6xl space-y-12">
        {/* Hero Section */}
        <div className="text-center space-y-4 py-10">
          <h1 className="text-5xl md:text-7xl font-bold tracking-tighter text-transparent bg-clip-text bg-gradient-to-b from-white to-slate-400">
            Real World Assets on <span className="text-amber-500">Solana</span>
          </h1>
          <p className="text-lg text-slate-400 max-w-2xl mx-auto text-balance">
            Excelsior (XLS) links crypto liquidity to premium Real Estate.
            Trade, Stake, and Earn Lux-Yields instantly.
          </p>
        </div>

        {/* Dashboard */}
        <RwaDashboard />

        {/* Action Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          <div className="space-y-6">
            <div className="prose prose-invert">
              <h2 className="text-2xl font-bold text-white">Market & Swap</h2>
              <p className="text-slate-400">
                Exchange your Luxor (LXR) utility tokens for Excelsior (XLS) Asset tokens.
                30% of LXR is burned instantly, 70% secures the asset backing.
              </p>
            </div>
            <SwapInterface />
          </div>

          <div className="space-y-6">
            <div className="prose prose-invert">
              <h2 className="text-2xl font-bold text-white">Staking Vault</h2>
              <p className="text-slate-400">
                Stake your XLS to earn dividends generated by the underlying real estate portfolio.
                Yields are paid in LXR.
              </p>
            </div>
            <StakingInterface />
          </div>
        </div>
      </div>
    </main>
  );
}
